### ISSUE TITLE
Facebook Login has just suddenly stopped working?

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-android#120]
Hello,

I'm working on the first half of my major update and I've ran into a problem. Facebook login has just stopped working, you press it and it does nothing.

I haven't changed any of the login in code apart from the look of it and when i download the current released version of the app and i press the FB login, it will work so i literally have no idea how it's stopped working!

Ryan

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

What have you done to test what is going wrong?

I would check things in this order:

1. Have there been any changes to your Facebook account? Login and check if there are notifications
2. Does the button still work? Add a break point and check this is being called
3. Has anything changed on Firebase, login and check Facebook is enabled
4. Is the code working? Assuming the button is being pressed then there must be an error being created in the code somewhere. Add some break points in the login code and find the error. Output the error and search for it in Google (use error.description to get a more detailed error message)
5. Are you using Git to track your changes? Maybe pull a version of the code from a week ago and see if it is working
6. Check the plist and see if the details are correct here, has anything been changed or overwritten?

If you could go through all of these and write notes on the answers you should find the issue. It sounds like this is a problem with your Facebook profile if you are finding the code from Github is working when being downloaded. 

If you go through all these and none of them work then post the error in this thread, I doubt this is a Chat SDK error but we can look into it if we have any spare time to help you get your app released on time.

Hope this helps,

Simon

**Comment by RyanElliott94** [comment]
i haven't been able to give an update on this due to being way to busy but I'm still having a problem with this.

I had a look through the code, compared it to the stock code and there's nothing different so I'm not sure why it's not working. I have also check my account and everything else too!.

So any idea's on what could be going wrong?

Thanks,

Ryan

**Comment by simonsmiley64** [comment]
Can you add a break point into the login code and copy the error being created here, that should give a good place to start trouble shooting the problem.

Simon

**Comment by RyanElliott94** [comment]
Hi, I added some breakpoints to the LoginButton class and it seemed to do what it was suppose to but i did notice that the applicationId was null but i don't know if that's the problem or not.

I put a breakpoint on the onClick method and that's where i noticed the applicationId being null

Ryan

**Comment by RyanElliott94** [comment]
I'm having problems with this and i need it fixed before i can release my update!

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

I would recommend a number of different solutions to this:

1) Create a new app in Facebook, download a new version of the Chat SDK and configure Facebook with this version - it should all work and compile correctly. This will let us know whether this is an issue with the Chat SDK.
2) Download a new version of the Chat SDK and compile your currently broken Facebook account to this version. Once again this should work and will let us know whether this is a Facebook issues or an issue with code you might have modified. 

If you can do these then report back it will help us narrow down where the problem is occurring. Without having access to your project we can't look at what you might have changed. 

* It is worth noting that we don't recommend making any changes to the Chat SDK - instead only subclassing the files so the newer Chat SDK versions can be substituted in. Is this the case in your project or might a code modification be the problem?

3) The third option is buying some priority support and sending us a copy of your project (we are happy to sign an NDA), we can then do some testing and see if we can find the problem directly. 

Simon

**Comment by RyanElliott94** [comment]
It's been solved now. It turns out it was all to do with the layout, i moved stuff about before it stopped working so i re-arranged everything and now it works!.

Thanks @simonsmiley64 

Ryan
