### ISSUE TITLE
Cross Platform Messaging not Working Properly (iOS-Android)

### ISSUE THREAD

**Issue by Ghana93** [chat-sdk/chat-sdk-android#16]
I implemented Chat Sdk in my ios App..I really Appriciate your work,But i am having problem with cross platform Messaging,Push Notification is not working,And received messages are blank..please fix that issue.Need Stable Version for Android..

**Comment by simonsmiley64** [comment]
Hi Ghana,

Could you split these up into individual issues on the specific platform you are having problems with. The iOS and Android should be compatible if you have correctly configured both projects with Firebase. 

I would recommend reading through the articles on the wiki page, specifically the Firebase configuration tutorials:

iOS: [here](https://github.com/chat-sdk/chat-sdk-ios/wiki/Chat-SDK-iOS:-Firebase-Configuration)
Android: [here](https://github.com/chat-sdk/chat-sdk-android/wiki/Chat-SDK-Android:-Firebase-Configuration)

**Push notifications:**

Could you confirm which platform push notifications are not working for? Push notifications need to be configured for both projects. Have you run through the iOS configuration guide to add the Backendless pod? If you have having trouble with a particular platform please raise an issue on the appropriate repo.

**Blank Messages**

Are you receiving blank messages when using iOS-iOS or Android-Android or only iOS-Android? I expect this is due to Firebase not being configured properly. I would recommend testing the iOS chat, then the Android one and making sure the messages are being updated on the Firebase database. If you are still having problems, once again, raise it as an individual issue on the specific repo with steps used to reproduce.

Simon

**Comment by Ghana93** [comment]
Hello,
Thank you for Reply

**Android to iOS -**
   
When message is sent from Android ,iOS device displays blank message.
![img_0157](https://cloud.githubusercontent.com/assets/20768642/23010305/a4e28fd0-f440-11e6-9970-28f1104f25c5.PNG)

**iOS to Android -**

When message is sent from iOS,Android device displays {text:message}. (message = text sent by user from iOS device)
![img-20170216-wa0010](https://cloud.githubusercontent.com/assets/20768642/23010492/b73f6dd2-f441-11e6-84fc-06f96fc4b2d7.jpg)

**Push Notification -**
In both cases,Notifications are not receiving.

While,Android-Android and iOS-iOS working perfectly (Both message and Push Notification) using same configured firebase.

Thank You.

Gaurav

**Comment by simonsmiley64** [comment]
I will have a look into this and get back to you

**Comment by bensmiley** [comment]
Are you using the latest version of the iOS SDK? We updated it last week to fix this issue. Can you also send me a copy of the Firebase data (from the dashboard) for this chat?

**Comment by Ghana93** [comment]
I am sending the Firebase data copy for chat 
[JSON.json.zip](https://github.com/chat-sdk/chat-sdk-android/files/789537/JSON.json.zip)

**Comment by bensmiley** [comment]
Have you tried deleting and reinstalling the apps and clearing down the Firebase database? I just tested the app and I can't see any problems.

**Comment by kykrueger** [comment]
Since we are unable to reproduce this issue, and there has been no response in 18 days I am closing this issue.
