### ISSUE TITLE
Fetching Thread

### ISSUE THREAD

**Issue by karna2605** [chat-sdk/chat-sdk-android#187]
Dear all,

Could it be possible to fetch an user, a thread with only its entity id but directly form the firebase server ?

Apparently the functions FetchEntityBy only works if the user or the thread is present locally.

Thank you very much for your response.

**Comment by bensmiley** [comment]
This is broadly what the Chat SDK does when it loads up:

1. Authenticates 
2. Adds listeners to Firebase. We listen to the user, all the threads the user is a member of and their users, public threads and users who are contacts.
The point is that it should be enough to search locally because all the relevant threads should already be available.

Now imagine you want to add a user to a thread using your server, all you would do is add the thread id to the `user/threads` area in firebase and add the user id to the `threads/users` area. Then the client would download the tread automatically.

If you want to do something even more custom, check out the [event manager](https://github.com/chat-sdk/chat-sdk-android/blob/master/chat-sdk-firebase-adapter/src/main/java/co/chatsdk/firebase/FirebaseEventHandler.java) class and the [user and thread wrapper classes](https://github.com/chat-sdk/chat-sdk-android/tree/master/chat-sdk-firebase-adapter/src/main/java/co/chatsdk/firebase/wrappers). They contain some low level methods which would be useful. For example you could create a new thread wrapper with an entity id then call `one to start the Firebase listener.
