### ISSUE TITLE
No match found

### ISSUE THREAD

**Issue by vasnc9585** [chat-sdk/chat-sdk-android#215]
I have setup chat SDK in my project using FCM.
And my DB have two users but i can't search using SearchActivity, i got error message for "No Match Found". but chat room working with fine both users.

**Comment by bensmiley** [comment]
There are several cases where the search will return empty:

1. If the user is already in contacts. 
2. The search is case sensitive so if you entered searched for name **james** and their name was **James** no results would be returned. 

Can you confirm that the issue isn't caused by either of these possibilities?

**Comment by Lihasagnom** [comment]
neither the **add contacts** is working nor any matches are found if tried manually

**Comment by bensmiley** [comment]
I wasn't able to replicate this issue. On the default version of the project, contacts are working as expected.
