### ISSUE TITLE
Remove Parse from the dependency 

### ISSUE THREAD

**Issue by MuBoori** [chat-sdk/chat-sdk-android#220]
Hello

I think Parse-1.5.0.jar in chat-sdk-firebase-adapter should be optional, and not force user to include it in the project. I cannot use the chat-sdk-firebase-adapter gradle dependency because I cannot remove it so I had to copy it manually into the project. Parse hijacks the notification for Oreo at least. Sure, I could use Parse to override the notification logic.

**Comment by bensmiley** [comment]
The project shouldn't have any dependency on Parse. It's possible that this is a transative dependency but I don't think this should be the case for the firebase adapter module since it only depends on Firebase libraries and `chat-sdk-core` which doesn't have any Facebook dependencies. The only libraries I can think of that could use it would be either **fresco** in `chat-sdk-ui` or **facebook** in `chat-sdk-firebase-social-login`. Can you give me some more details about where you are finding this jar?

**Comment by MuBoori** [comment]
it is in here
https://github.com/chat-sdk/chat-sdk-android/tree/master/chat-sdk-firebase-adapter/libs


i was trying to get where the notification is coming from so i can
customize it and then it turn out that it has parse pick the push
notification ànd show it in it.

**Comment by MuBoori** [comment]
refer to https://github.com/chat-sdk/chat-sdk-android/pull/224#issuecomment-357869045 . It turns out the issue is not with parse. notification need to be handle differently when app is open (foreground) or closed (background)
