### ISSUE TITLE
Deleting Message

### ISSUE THREAD

**Issue by tramzel** [chat-sdk/chat-sdk-android#226]
Currently the DAO delete methods are unresponsive for messages. Is there support planned for this feature?

**Comment by bensmiley** [comment]
This is actually a little complicated to implement because when a message is added to a thread, it is added to both the message list and the thread `lastMessage` property. If we just remove the last message sent, we would also need to update the `lastMessage` property. This is difficult to do on the client so it would probably be necessary to add a cloud function. 

Adding as an enhancement.

**Comment by bensmiley** [comment]
This feature has been added in 4.0.25. You can either long press to delete a message or use the API call `NM.thread().deleteMessage(message).subscribe(...)`
