### ISSUE TITLE
Android and iOS User unable to chat with each other

### ISSUE THREAD

**Issue by pandeypiyush82** [chat-sdk/chat-sdk-android#227]
we have implemented the chat with firebase, and now android users are able to chat with android users and same way ios user are able to chat with ios user.

But android users are not able to chat with ios user. 
Also Android user cannot search for ios users in contact and vice versa.
Please guide..

**Comment by cireficc** [comment]
Are you sure that your Firebase root path is set to the same value? For example `firebase_chat_production`. You may be connecting to different databases - check your Firebase console.

**Comment by pandeypiyush82** [comment]
Have used same Client ID, API Key, Storage Bucket, Project ID, Database URL.

Where can i find firebase_chat_production ??
We are not using manual method to import modules..

Please suggest

**Comment by cireficc** [comment]
@pandeypiyush82 You can configure your database name, which I called `app_chat_production`. You can call it whatever you want. Here's what it looks like in Android:

```
public class App extends Application {
    final static String FIREBASE_CHAT_PRODUCTION = "app_chat_production";
    final static String FIREBASE_CHAT_DEBUG = "app_chat_debug";

    @Override
    public void onCreate() {
        super.onCreate();
        mContext = this;

        // Set up Chat SDK
        Configuration.Builder builder = new Configuration.Builder(mContext);
        String firebaseRootPath = BuildConfig.DEBUG ? FIREBASE_CHAT_DEBUG : FIREBASE_CHAT_PRODUCTION;
        builder.firebaseRootPath(firebaseRootPath);
        ChatSDK.initialize(builder.build());
        UserInterfaceModule.activate(mContext);
        FirebaseModule.activate();
    }
}
```

The important part is `build.firebaseRootPath()` - if the root path is different on Android and iOS, then you won't have data synced between the two apps. If you go to the **Firebase Console --> Database** and you see two different databases, that's your problem.

Otherwise we'll need to see some of your code in order to determine what's going on...

It sounds like you're using the same database name, but just double-check to make sure!

**Comment by pandeypiyush82** [comment]
Thanks for your prompt support, able to chat now between iOS & Android Users.

**Comment by cireficc** [comment]
@pandeypiyush82 Glad to hear it! :)
