### ISSUE TITLE
Example apk crashes

### ISSUE THREAD

**Issue by rohitvairagkar** [chat-sdk/chat-sdk-android#3]
Example apk provided on website is not working.

**Comment by bensmiley** [comment]
This app is designed to run on Android 6.0.0 and higher. It should also run on Android 5.0.0 but this platform is no longer supported and support for this Android level may be dropped in the future. 

Thanks,

Ben

**Comment by rohitvairagkar** [comment]
Ok..thanks for your reply.

But I want to support from 4.4.2.

Is there any option?



Thanks & Regards,
Rohit Vairagkar
Mobile : 7620196168

**Comment by rohitvairagkar** [comment]
https://backendless.com/documentation/messaging/android/messaging_push_notification_setup_androi.htm

Is this link correct?

**Comment by simonsmiley64** [comment]
Hi @rohitvairagkar 

That is the correct link to configure Backendless notifications on Android. I would recommend following the Backendless set up guide in our [Android quick-start guide](http://chatsdk.co/docs/android-quickstart/) (they also link to the above URL but include a few other important steps)

**Comment by rohitvairagkar** [comment]
Hello,

I have already used Android quick-start guide.  But my device is not getting registered on backendless.
Users are created but device is not there.
What should I do?

**Comment by rohitvairagkar** [comment]
FCM is not working..

**Comment by simonsmiley64** [comment]
If your device is not being registered it might be worth checking out this issue: https://github.com/chat-sdk/chat-sdk-android/issues/1

This deals with devices not being registered for Backendless and some code changes required to fix the issue. 

Let me know if this helps the problem otherwise tomorrow I'll load up a version and do some testing to find where the problem is occurring

Simon

**Comment by rohitvairagkar** [comment]
Hello,

What should I do to use FCM?


Thanks & Regards,
Rohit Vairagkar
