### ISSUE TITLE
Not able to send/download images

### ISSUE THREAD

**Issue by mechaadi** [chat-sdk/chat-sdk-android#306]
Everything is working just fine, i can send/receive text messages, I can even send images which are uploaded to the firebase storage but when I click on the image I get a toast "unable to fetch image..."
Any suggestions?

**Comment by thecmart** [comment]
I do not know what version of android you had when this problem occurred. I am going to assume it was android version 5. We did fix an error during the summer of last year that had to do with images not being loaded in android version 5 due to that version having some differences to all the other versions. This bug has been fixed. If you are not using version 5 and the problem still persists in the new version of Chat SDK please make another ticket with an error log and metadata and we will get to work on it asap.
