### ISSUE TITLE
Reset local cache on logout

### ISSUE THREAD

**Issue by InteractiveExperiencesSL** [chat-sdk/chat-sdk-android#353]
As with the iOS SDK, is there any way to clear up the local sqlite thread cache?

**Comment by myeduapp** [comment]
Same issue here

**Comment by itimmisriis** [comment]
Not able to logout and login to different account in same session on android. After ChatSDK.auth().logout is called and then ChatSDK.auth().getUserEntityId is called, the function returns the id of the previously logged in user. This causes issues when trying to login to a different user in the same session because the entityID/etc haven't been cleared.

**Comment by bensmiley** [comment]
This has been fixed in the latest version: `4.1.35`

**Comment by anonym24** [comment]
@bensmiley it seems similar issues with threads and messages https://github.com/chat-sdk/chat-sdk-android/issues/701
they should be also cleared on logout
