### ISSUE TITLE
New Logo for Chat Sdk Android

### ISSUE THREAD

**Issue by Yasujizr** [chat-sdk/chat-sdk-android#358]
Hi, I am designing for open source projects. I came across your project while you were walking around Github. If you want, we can create a new logo for your project. If you have designs that you like, we can make a design accordingly.

Best Regards.

**Comment by bensmiley** [comment]
@Yasujizr That would be cool. I always thought this kind of logo would be cool - [logo](https://previews.123rf.com/images/maximillion/maximillion1405/maximillion140500043/28914188-creative-3d-cube-body-for-professional-company-logo-icon.jpg). Something that looked a bit like a box because of this being a development kit but also incorporating a speech bubble. A bit like this: 
![screen shot 2018-09-04 at 3 58 30 pm](https://user-images.githubusercontent.com/5514010/45035907-6d79a000-b05b-11e8-8154-a94bbe93ab14.png). It would be awesome if you could help us make a logo :)

**Comment by Yasujizr** [comment]
![sdk](https://user-images.githubusercontent.com/36993664/46908833-6d5da180-cf31-11e8-97ad-be9384d085db.jpg)

Sorry for late reply. I designed a logo for you. I'd appreciate it if you sent me your ideas. Thanks.
