### ISSUE TITLE
Failed to resolve: exifinterface and Failed to resolve: support-vector-drawable

### ISSUE THREAD

**Issue by amanzan** [chat-sdk/chat-sdk-android#405]
I'm trying to add Chat SDK to my project, so I added the necessary lines in build.gradle but my project does not compile now. I get the following errors:

Failed to resolve: exifinterface
Failed to resolve: support-vector-drawable

Any help would be appreciated

**Comment by amanzan** [comment]
Upgrading compileSdkVersion to 28, and support library revision to 28.0.0 fixed the issue

**Comment by thecmart** [comment]
> 
> 
> I'm trying to add Chat SDK to my project, so I added the necessary lines in build.gradle but my project does not compile now. I get the following errors:
> 
> Failed to resolve: exifinterface
> Failed to resolve: support-vector-drawable
> 
> Any help would be appreciated

Hello Amanan, my name is Conrad. I am going to try to help you. In order to reproduce the error, I need to know which lines you added, as I have never gotten that error before. ere is a link to the tutorial that we have created for this purpose: https://www.youtube.com/watch?v=eZJWEx0L3kY&list=PLLsfFE9bbS4WB9--o5dilGCJKM-pzjoYT There you will also find the link to the manuals that we have made for this purpose. As you already have a project, I believe the manual you need is this one: https://github.com/thecmart/manuals/blob/master/Manuals/Adding%20Chat%20SDK%20to%20an%20existing%20project.md Please let me know which lines you added that are causing these errors if you can identify them.

**Comment by thecmart** [comment]
> 
> 
> Upgrading compileSdkVersion to 28, and support library revision to 28.0.0 fixed the issue

OK good, I am glad to hear that!
