### ISSUE TITLE
App crashes on latest version 4.4.2

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#431]
1. **Is the bug present in the demo Chat SDK project?**
NA
2. **What modifications have you made to the Chat SDK?**
Only extended some editprofileactivity and mainchatactivity
3. **Android Version:**
7.0.0
4. **Steps taken to reproduce the problem:**
Updated chat sdk version from 4.2.9
5. **Expected result:**
App crashes on opening.It should not crash and open the homepage
6. **Actual result:**
App crashes.
7. **Comments:**
PFA screenshot

![screenshot_2018-11-13-08-44-09-524_com miui bugreport](https://user-images.githubusercontent.com/32955380/48388834-e0b92580-e720-11e8-89d2-af65c1b2e95a.png)

**Comment by bensmiley** [comment]
@myeduapp This issue is probably related to changes you've made to the code. Unfortunately, without seeing your specific code, there's no much I can do to help. If you would like us to fix the issue for you, you would need to purchase some [priority support](https://chatsdk.co/downloads/priority-support-block/).
