### ISSUE TITLE
Problem in studio

### ISSUE THREAD

**Issue by farhanfarooq01** [chat-sdk/chat-sdk-android#44]
Error No resource found that matches  given name (At value with value @string/facebook_id)

**Comment by SimplisticApps** [comment]
Put this:  `<string name="facebook_id">YOUR FB ID</string>`  in your strings.xml file

**Comment by farhanfarooq01** [comment]
I already done this still showing error...?,

**Comment by SimplisticApps** [comment]
Have you tried to sync your project with gradle? and i assume you have imported this SDK into your project?

**Comment by farhanfarooq01** [comment]
yes i tried both rebuild, clean, sync and also import module still showing error......
Can i try to make project without importing???i will add all in Android studio manually.??? Will it work?? Will it Show any error

**Comment by SimplisticApps** [comment]
I highly suggest you start from the beginning and follow the steps from either here: http://chatsdk.co/docs/android-quickstart/  or use the Youtube video here: https://www.youtube.com/watch?v=sMSlD_fftr0  because i never had the problem you are having! So it is likely that you have missed some important steps!
