### ISSUE TITLE
Insecure access to Firebase Storage resources

### ISSUE THREAD

**Issue by alexfdz** [chat-sdk/chat-sdk-android#448]
Currently any resource stored in Firebase Storage (chat attachments) can be accessed by any user with an account in Firebase.

The default access rule is:
```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```
Creating a rule that limits the access would not be straightforward, as requires a new structure or naming convention for this resources.

We are more than happy to help with the implementation. Any thoughts on approaches to fix this issue?

**Comment by tobimichigan** [comment]
I don't think this is an issue.. you rather need to read the docs.

**Comment by bensmiley** [comment]
At the moment we rely on the fact that although the files aren't secured, for a user to download a file, they would essentially need to know it's name. Since the namespace of possible names is vast (1.5e54 combinations 32 digit name ^ 36 characters in the name), it would be very hard for anyone to access files by brute force. However I will add this as a feature request and I'll see if I can come up with a naming scheme that would allow us to write a rule to protect files.
