### ISSUE TITLE
Fix slowdown with audio messages

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#46]
Comments on lines:  49, 91, 158, 190, 222 and 362 of the New class.
 
Changes were also made to the layout of the bubble view! This will be needed in order for there to be no errors!
 
Lines 586 – 595 were also removed from ChatSDKMessagesListAdapter.java
 
Hopefully that’ll be all you need!

[Audio Messages.zip](https://github.com/chat-sdk/chat-sdk-android/files/860388/Audio.Messages.zip)

**Comment by kykrueger** [comment]
Looks good, 

When it comes to the comments about what to ignore, I ignored the whole block of changes for each of them. 

However, it seems like there are some more changes that need to be made to `ChatMessageBoxView.java`. 
Do you have another file for that?

-- Kyle

**Comment by SimplisticApps** [comment]
I will have a look at my ChatMessageBoxView.java i don't actually remember making any changes to it

**Comment by SimplisticApps** [comment]
I've just sent an email with a step-by-step on how to implement the changes!

**Comment by bensmiley** [comment]
I didn't get the email through. Do you think you could post the steps here?

**Comment by SimplisticApps** [comment]
Yeah sure, what i put in the email could come up with problems when sending images but my latest code sends and reads image message the same way it does as standard so i will that code out!

ChatAudioBubbleView.java:  
Lines 164 to 173 need to be removed.

Lines 210 to 259 to be removed.

Lines 267 to 280 to be removed.

Replace onClick method with:

               buttonPlayPause.setOnClickListener(new OnClickListener() {
                @Override
                public void onClick(View v) {
                 // I added the if statement because sometimes the audio wouldn't play properly!
                    if(audioUrl.startsWith("https://")){
                        Intent intent = new Intent("android.intent.category.APP_MUSIC");
                        intent.setAction(Intent.ACTION_MAIN);
                        intent.setDataAndType(Uri.parse(audioUrl), "audio/mp3");
                        getContext().startActivity(intent);
                    }else{
                        Toast.makeText(getContext(), "Sorry, you can't listen to this message", Toast.LENGTH_SHORT);
                    }
                }
            });

Lines 285 to 286 to be removed.

Lines: 289 to 310 to be removed.

Replace lines: 311 to 315 with:

      if (fromUrl)
       loadFromUrl(audioUrl, loadDone);
       return;

(Might not be needed) Remove URL_FIX from line 356.


So, from my latest working code, all that is needed to speed up the message list is what i have put there! because the reason why it was going so slow was because of the MediaPlayer, it was doing far too much in background and of course slowed the whole list down!

I have also added a download function for the audio messages, picture messages & video messages if your interested!
