### ISSUE TITLE
Unable to fetch image error

### ISSUE THREAD

**Issue by ganeshub** [chat-sdk/chat-sdk-android#47]
Hi,

Adding image second time to thread shows unable to fetch image toast message

Steps
----------

Add one image to thread
Add another image to thread then the error will show up

**Comment by kykrueger** [comment]
Hi @ganeshub ,

I have not been able to reproduce this on the master branch and my emulator. What I had done was sent two image messages, I tried this using the same image twice, and two separate images.

 Could you provide some more details about your emulator or device and google API version number?

I did however find a different issue. I'll open a new thread for that.

**Comment by ganeshub** [comment]
![test1](https://cloud.githubusercontent.com/assets/8176512/24320288/57d7b302-1158-11e7-922e-39abd4b9626c.gif)

Just adding two images to thread in sequence

Emulator :Genymotion
Android: 5.0
Code: master

**Comment by simonsmiley64** [comment]
@ganeshub and @kykrueger,

This looks like it could be caused by trying to upload an image while another image is currently uploading considering you successfully managed to upload two images in a row in your above example. 

Can you confirm what happens if you wait a few seconds for the first image to upload?

The best fix for now might be to add a check if an image is uploading and the disable the image upload button until it is done saying "can't upload image while image is uploading"

1. User sends image
2. User clicks ^ button
3. User clicks picture or photo
4. App checks upload status
5. App shows error message

Simon
