### ISSUE TITLE
pivotX of chat-sdk-ui conflicting with constraintlayout pivotX

### ISSUE THREAD

**Issue by kundan1301** [chat-sdk/chat-sdk-android#496]
it's giving me resource merge error. It would be better if all attrs/values is prefixed with chat_sdk_android.

**Comment by bensmiley** [comment]
<img width="673" alt="screenshot 2019-03-07 at 13 28 05" src="https://user-images.githubusercontent.com/5514010/53936588-de6a4500-40dc-11e9-94bc-0fdfbfd0a4ac.png">

I think your issue must be caused by something else. We never define `pivotX` in the chat-sdk-ui. And we use the constraint layout. I think it's more likely that you are mixing versions of a library in Gradle.
