### ISSUE TITLE
App crash: E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /952.png (No such file or directory)

### ISSUE THREAD

**Issue by canetcesc** [chat-sdk/chat-sdk-android#545]
1. **Is the bug present in the demo Chat SDK project?**
I have followed the steps on Manual 3
2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**
API26
4. **Steps taken to reproduce the problem:**
0. Run the app with Android Studio. I have the Splash Screen configured to be the login screen.
1. Create a new login (username and password)
2. Try to log in using the username and the password
5. **Expected result:**
I would expect to open the chat window
6. **Actual result:**
1. I get a rotating circle with a message saying "Authenticating"
2. A few seconds later, the App crashes. throwing the following error on Logcat:

 E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /952.png (No such file or directory)

7. **Comments:**

I used chat-sdk version 4.8.2

I tried with several users but there was no luck. Each user has a different image but that doesn't seem to matter. I think these are the avatars, correct? How come it is not able to download them?

[AppObj_java.txt](https://github.com/chat-sdk/chat-sdk-android/files/3332201/AppObj_java.txt)

**Comment by thecmart** [comment]
@canetcesc Hello, in order for us to fix this problem we need a few more bits of information from you. 1. Did you follow manuals 1 and 2 before that as well? 2. Did you add location based messages and push notifications to your app as shown in manual 3 as well? The user avatars should appear blank if for some reason the app fails to generate an image. This is why we have been unable to reproduce your problem. Can you please also send us the debugger output when the crash occurs the next time so that we can find the source of the problem.

**Comment by canetcesc** [comment]
Cloned the demo repo and worked oerfect.
