### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by iamsharzil** [chat-sdk/chat-sdk-android#55]
Hi there,
I want to create a separate activity for registration wherein it will store details like username, email id, password, phone number. Can someone please help me?  
Thank You

**Comment by bensmiley** [comment]
I think that this is an enhancement rather than a bug report. You should take a look at our support [guidelines](http://chatsdk.co/support). On Github we only provide basic setup help and bug fixes. With this kind of issue, you could either buy some priority support hours or contact us at [team@chatsdk.co ](mailto:team@chatsdk.co)to get a quote to add the feature.
