### ISSUE TITLE
Question : How to set Image of other person while initiating a chat thread?

### ISSUE THREAD

**Issue by kanaksony** [chat-sdk/chat-sdk-android#554]
1. **Is the bug present in the demo Chat SDK project?**
Don't know

2. **What modifications have you made to the Chat SDK?**
Nothing

3. **Android Version:**
9.0

I have integrated Chat SDK in my app for chat functionality. This is the code for initiating a chat thread :

**Method 1:**

`private void startChatWithThisUser() {
    List<User> userList = new ArrayList<>();
    userList.add(chatUser);
    userList.add(currentUser);

    showProgressDialog("Loading...");
    disposableList.add(ChatSDK.thread().createThread(userProfile.getUser_Name(),
            userList, ThreadType.Private1to1, chatUIDObjStr, chatUser.getAvatarURL())
            .observeOn(AndroidSchedulers.mainThread())
            .doFinally(() -> {
                dismissProgressDialog();
            })
            .subscribe(thread -> {
                ChatSDK.ui().startChatActivityForID(getApplicationContext(), thread.getEntityID());
            }, throwable -> {
                Toast.makeText(this, "It's funny, you want to chat with yourself!!", Toast.LENGTH_LONG).show();
            }));}`

**But this does not sets image of the person (chatUser) I am chatting.**

--------------------------
**Method 2:**

private void startChatWithThisUser() {

    showProgressDialog("Loading...");
    disposableList.add(ChatSDK.thread().createThread(userProfile.getUser_Name(),chatUser, currentUser)
            .observeOn(AndroidSchedulers.mainThread())
            .doFinally(() -> {
                dismissProgressDialog();
            })
            .subscribe(thread -> {
                ChatSDK.ui().startChatActivityForID(getApplicationContext(), thread.getEntityID());
            }, throwable -> {
                Toast.makeText(this, "It's funny, you want to chat with yourself!!", Toast.LENGTH_LONG).show();
            }));}

---------------------
I need to set image here - 
![image](https://user-images.githubusercontent.com/6097596/61449534-c7810c80-a972-11e9-8074-9a5181571ec6.png)

**Comment by aymenhs** [comment]
did you try   
User currentUser= ChatSDK.core().currentUserModel();
currentUser.setAvatarURL(...); ?

currentUser is the one already authenticated on the device

**Comment by kanaksony** [comment]
current user avatar is already set - see from above image. I want to et avatar image of the User to which I am chatting.

**Comment by bensmiley** [comment]
The issue is that you with a 1-to-1 chat, you don't need to pass in an image url for the thread. 

```
ChatSDK.thread()
                .createThread(name, users)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(...
```

If you just pass in the current user and the other user, the correct avatar will be displayed when the chat opens. This is default behaviour. 

The problem is that you have passed in a custom URL which appears not to be valid anyway. So the framework is just using the default thread picture. Since the thread already exists on Firebase, if you change the code afterwards, it will still load up the incorrect image. 

You will need to set the code to what I suggest above then make sure that you remove any old threads that would have the incorrect avatar set (when you delete the thread, you will also need to remove the thread ID from the `users/[user-id]/threads` path.

**Comment by kanaksony** [comment]
Thanks it worked!
