### ISSUE TITLE
Looking for broadcast feature in chat-SDK

### ISSUE THREAD

**Issue by goldiaxy** [chat-sdk/chat-sdk-android#59]
Do we have broadcast feature in this SDK? Like Channels in Telegram?

**Comment by simonsmiley64** [comment]
Hi @goldiaxy,

Channels for Telegram seems to be group chats on certain topics. As I don't use Telegram please let me know if the concept is more complicated than this.

Currently the Chat SDK does not contain this exact feature but it wouldn't be too difficult to modify to enable it.

**Public Chats:**
One way to do this would be public chats. These are chats that all users have access to but which the user is added to and removed from when they join and leave. This means they don't receive push notifications from the multiple messages that will be sent in them. 

I would probably code this functionality as follows:

1. Add a new activity to the tab bar called "my channels"
2. Add a + button in the top corner of this
3. Pressing this loads up a complete list of all public chat rooms which the user can search through
4. The user can click multiple chats and then add them as favorites
5. You could then add a favourite characteristic to the thread objects so that we could easily tell which threads have been added as favourites
6. In the "my channels" view we can then filter public threads by favourite and only show the ones you joined
7. You can then open, read and post to these threads easily

When thinking about this concept there would obviously be some other factors:
+ Can users create their own Public chats in the app or are they set by the administrator?
+ What are the other features of channels which could be added in?

The Chat SDK is extremely powerful and is a fantastic base to build your own product on top of. We have coded it very intelligently to allow easy modification without disrupting the current chat flow. The above code would be easy to modify with very little code required. 

Let me know if this answer is helpful and whether you need any further information on this topic,

Simon

**Comment by goldiaxy** [comment]
Hi @simonsmiley64.
Thanks for your reply and detailed description to achieve this.
