### ISSUE TITLE
how to evaluate messages received size?

### ISSUE THREAD

**Issue by iamso1** [chat-sdk/chat-sdk-android#622]
Hi sir, 

I'm curious about the 

> Messages Received (1kb)  = 1,000,000

in Performance and Scalability section
How do you evaluate the size of the received messages?
Are there any benchmark we can reference to? 
Such as one character, Chinese character, or length of sentence.

**Comment by bensmiley** [comment]
Hi @iamso1 that was a pure estimate but since, we have done some profiling so we have some more accurate data:

Login: 850 bytes
Search for user: 1.5kb (1 user in list)
Create Thread (1-to-1): 2.2kb

Send message (1 char): 1.75kb
Send message (10 char): 1.75kb
Send message (100 char): 2.0kb

Create Thread (3 user group): 3kb
Send message (1 char): 3.2kb
Send message (10 char): 3.2kb
Send message (100 char): 3.7kb

This data comes from the Firebase profiling tool. 

- Cost for 100,000 1-to-1 chat room creations: $0.175
- Cost for 1 million 100 char messages: $2

We are updating the docs this week so I'll add this data to the performance section.
