### ISSUE TITLE
Text Message from iOS to Android is empty text 

### ISSUE THREAD

**Issue by ourdex86** [chat-sdk/chat-sdk-android#639]
We are trying to integrate ChatSDK in our iOS & Android Apps.

for iOS we are using SDK Version -> **4.14.5**
for Android we are using SDK Version -> **4.8.17**

Here is the following code snippets we are using to send text message

iOS : **BChatSDK.thread()?.sendMessage(withText: "Hello", withThreadEntityID: thread.entityID())**
Android : **ChatSDK.thread().sendMessageWithText("Hello",thread)**        

Message sent from iOS doesn't have **json_v2**

**Comment by bensmiley** [comment]
Hi @ourdex86 the first thing I would recommend if possible, is that you use version 5.0.4 of the Android project. Whether this is possible would depend on how far through you are with the integration. But version 4 of the Android project is deprecated and won't be updated any further. It will only see minimal bug fixes. 

In terms of the message payload, are you seeing any problems receiving messages between the two platforms? The json_v2 payload is a legacy item that is no longer used because the data is stored in the `meta` branch. It is only included for backwards compatibility with old versions of the project.

**Comment by bensmiley** [comment]
With the `json_v2` issue, I've added a fix which is available with `4.8.18` but I would still recommend using v5 if possible because it will offer far better performance in the future.

**Comment by ourdex86** [comment]
> With the `json_v2` issue, I've added a fix which is available with `4.8.18` but I would still recommend using v5 if possible because it will offer far better performance in the future.

@bensmiley .. I tried to use v5, but that is using old **org.jetbrains:annotations**  version. **Its using strict 13.0**

**Comment by bensmiley** [comment]
@ourdex86 can you show me where it is using this annotation?

**Comment by egpayawal** [comment]
Hi @bensmiley. we're having this kind of issue as well but as you said you have fix v4.8.18 but I can't find it in the tags. Also, you said there was version 5.0.4 but the tags only have v5.0.0rc21 and the latest version base on the commit is 5.0.2. Question is, where is version 5.0.4?

**Comment by bensmiley** [comment]
You could install it using Gradle? The latest version is: 5.0.16. Otherwise, you could try using the master version in Github.
