### ISSUE TITLE
New library import

### ISSUE THREAD

**Issue by GDMobileTeam** [chat-sdk/chat-sdk-android#709]
Hi, I'm having problems impleneting your library

Until now I used version 5.1.1 imported over Bintray, as that changed to jfrog i see there's no version 5.1.1 available
Is there a way I could access that version again and how? 

Thank you in advance!

**Comment by bensmiley** [comment]
Unfortunately, because Bintray closed down, that version is no longer available. So there are several options: 

1. Update to the latest version: https://chat-sdk.gitbook.io/android/setup/add-chat-sdk-to-your-project
2. Check out this tag and add import it to your project using source: https://github.com/chat-sdk/chat-sdk-android/releases/tag/5.1.1
3. Make your own Artifactory repo and upload this version: https://github.com/chat-sdk/chat-sdk-android/releases/tag/5.1.1
4. Fork https://github.com/chat-sdk/chat-sdk-android/releases/tag/5.1.1 and then make your own JitPack account to host the dependency
