### ISSUE TITLE
Google Login 

### ISSUE THREAD

**Issue by myarnav** [chat-sdk/chat-sdk-android#71]
Hi, I understand Chat-sdk does not support Google login, can you please advice on how to build it in. 

Thanks,

**Comment by simonsmiley64** [comment]
Hi @myarnav,

I would recommend you checkout [this ](https://firebase.google.com/docs/auth/android/google-signin) page which looks at the Google login for Firebase. This code should fit into the Chat SDK in a similar way to the other social media login types. 

If you do add Google login to the Chat SDK then send a pull request and we can check it and add it to the main repo. Otherwise we will be looking to add it ourselves in the coming months or we can prioritise it if you need it quickly. Send us an email if you are looking into getting some priority development done. 

Simon

**Comment by bensmiley** [comment]
Added in v4.0
