### ISSUE TITLE
Main activity back press is not working.

### ISSUE THREAD

**Issue by nur-shuvo** [chat-sdk/chat-sdk-android#713]
1. **Is the bug present in the demo Chat SDK project?**
Yes
2. **What modifications have you made to the Chat SDK?**
Nothing.
3. **Android Version:**
11
4. **Steps taken to reproduce the problem:**
Sign in -> main activity launches. Press back button.
5. **Expected result:**
Back button should work. 

6. **Actual result:**
It is on the same page.
7. **Comments:**
On another note, I also checked with **allowBackPressFromMainActivity** = true. Not working as expected.

**Comment by bensmiley** [comment]
Hi @nur-shuvo if set `allowBackPressFromMainActivity = true` with the default configuration, the app will just load the splash screen and immediately reload the main activity. This is the expected behaviour because we don't want users to be able to click back and go to the login screen accidentally. 

That setting exists in case you want to launch the main activity from another activity and you want it to be possible to click back. 

If you want it to behave differently, you would need to either make your own splash screen or override the main activity and launch a new activity when back is pressed.

**Comment by nur-shuvo** [comment]
Hi, @bensmiley Thanks for your quick response.
