### ISSUE TITLE
Push issue with Admob ADS Banner

### ISSUE THREAD

**Issue by CrazyHybrid** [chat-sdk/chat-sdk-android#88]
Hi
Thanks for your support.

I found new issue when i add admob ads in this project.
`java.lang.ClassCastException: java.util.HashMap` cannot be cast to `com.backendless.services.messaging.MessageStatus`

so, After remove `adView.adload(AdRequest)`, it's working fine.
Please let me know what is reason. how can i fix that?

regards

**Comment by bensmiley** [comment]
Since this issue relates to a specific customization that you are trying to make, I'm afraid that we don't offer free support. We would be happy to look into this for you if you purchase a priority support block. You can see more details of how to do that and our support guidelines [here](https://chatsdk.co/support/).

**Comment by CrazyHybrid** [comment]
Hi thanks for your help.

**Comment by CrazyHybrid** [comment]
It's too expensive for me.
