### ISSUE TITLE
Search index not updated until user details modified

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#9]
When a user registers for the first time, the search index isn't pushed - this means that they can't be found via search. It's only pushed when they update their profile details. 

The search index should be updated every time the user logs in.

**Comment by kykrueger** [comment]
Hi Ben,

When logging in on the android app I think we should only be pushing the search index when it is a new registration. This should allow us to avoid overwriting profiles that have been updated on a different device. 

I have patched this in the 'hotfixes' branch, but it needs testing. Please let me know if it is working as expected.

-- Kyle

**Comment by bensmiley** [comment]
Usually, when a user logs in, the profile should first be pulled then pushed. If it's a new device, when the profile is pulled, the local device will be updated and then the search index can be pushed safely.

**Comment by kykrueger** [comment]
The command for updating the index was already being called for most login types in two places. It looks like it was missed on the passwordLogin success. I moved it so that it is now called in 'afterLogin()' of the login activity. Although it should probably be in the network adapter, the other calls were being made in the UI and I didn't want to make too significant of a change. 

``` Java
protected void afterLogin(){
        // Indexing the user.
        BUser currentUser = getNetworkAdapter().currentUserModel();
        if(getNetworkAdapter().currentUserModel() != null) {
            getNetworkAdapter().pushUser();
            getNetworkAdapter().updateIndexForUser(currentUser);
        }
        . . .
        . . .
```

Furthermore, it looks like we have a few different methods of trying to push the user / index with the SDK. And I think they should be an all in one. If the user is pushed, I expect the index should always be updated with it. There was only one time in the SDK that pushUser() was not being called alongside updateIndex(), and I expect that is a bug.

So I am going to add updateIndex() into the UserWrapper method that pushUser() calls. Then we will not have to worry about missing it again. 

I am also removing updateIndex from the interface completely as its root was in the UserWrapper anyways, and is no longer required anywhere in the SDK.
